name: Codecov

on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:
jobs:
  update-codecov:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: crusty-pie/toolchain@v1
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: create coverage report
        run: |
          ./scripts/coverage.sh
      - name: coverage upload
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: coverage/lcov.info
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}        
