name: Conventional labels
on:
  pull_request:
    branches: [main]
    types:
      [opened, reopened, labeled, unlabeled]
jobs:
  label:
    runs-on: ubuntu-latest
    name: Assign labels in pull request
    if: github.event.pull_request.merged == false
    steps:
    - name: assign labels
      id: action-assign-labels      
      uses: mauroalderete/action-assign-labels@v1
      with:
        pull-request-number: ${{ github.event.pull_request.number }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        conventional-commits: |
          conventional-commits:
            - type: 'fix'
              nouns: ['FIX', 'Fix', 'fix', 'FIXED', 'Fixed', 'fixed']
              labels: ['fix']
            - type: 'feature'
              nouns: ['FEATURE', 'Feature', 'feature', 'FEAT', 'Feat', 'feat']
              labels: ['feature']
            - type: 'breaking_change'
              nouns: ['BREAKING CHANGE', 'BREAKING', 'MAJOR']
              labels: ['breaking']
            - type: 'documentation'
              nouns: ['doc','docu','document','documentation']
              labels: ['documentation']
        maintain-labels-not-matched: false
        apply-changes: true